In [1]:
from logic.gg_parser import ClubGGDataParser

In [2]:
club_id = 910171
parser = ClubGGDataParser(club_id)
parser.get_data()

[main] [2025-05-28 15:27:50] [INFO] - Getting Data From: C:\Users\USER\PycharmProjects\GGDataParser\resources\910171_20250512011607.xlsx

,AGENT_ID,AGENT_NAME,COUNTRY,ROLE,MEMBER_ID,NICKNAME,GAMES,HANDS,FEE,TOTAL_BALANCE
0,3314-4813,Natsich!,NaN,Player,3852-3098,Reg Eater,0,0,0.00,0
1,3314-4813,Natsich!,NaN,Agent,3314-4813,Natsich!,1,112,12.00,0
2,9817-5561,VIVIPUTZ[],NaN,Player,4686-9121,Enigam951,7,456,129.91,0
3,9817-5561,VIVIPUTZ[],NaN,Agent,9817-5561,VIVIPUTZ[],4,96,43.00,0
4,-,-,NaN,Manager,4517-4290,DaniDonk,17,1369,224.39,0
5,-,-,NaN,Player,7259-4548,Tal122,0,0,0.00,0
6,8831-1398,orchidk,NaN,Player,6251-5310,Shohaminio888,0,0,0.00,0
7,-,-,NaN,Player,3136-8163,ItoTheBigo,12,724,86.95,0
8,-,-,NaN,Player,7374-8621,lil nuts,3,337,76.29,0
9,3314-4813,Natsich!,NaN,Player,1154-1115,IDvir,4,118,33.14,0
10,8831-1398,orchidk,NaN,Agent,8831-1398,orchidk,2,115,41.76,0
11,8831-1398,orchidk,NaN,Player,5282-7593,Matan118,0,0,0.00,0
12,-,-,NaN,Player,3779-1229,Itay8764,0,0,0.00,0
13,6353-9124,AceHighBye,NaN,Agent,6353-9124,AceHighBye,0,0,0.00,0
14,-,-,NaN,Manager,3034-8358,Sheepment,12,614,214.64,0
15,4535-3656,YoY0Mama,NaN,Player,5218-9187,Rotem119,0,0,0.00,0
16,-,-,NaN,Player,3752-4991,HaMacabi,0,0,0.00,0
17,-,-,NaN,Player,9194-1695,NuMaaa2000,2,195,26.84,0
18,8831-1398,orchidk,NaN,Player,5687-1807,Kingkong325,0,0,0.00,0
19,4535-3656,YoY0Mama,NaN,Player,2922-3380,All_In_Dolev,0,0,0.00,0
20,9817-5561,VIVIPUTZ[],NaN,Player,9442-2093,VIVIPUTZ-JR,4,228,39.00,0
21,-,-,NaN,Player,6873-6696,Krane84,1,8,16.00,0
22,-,-,NaN,Player,2902-9205,nitayk,1,109,10.00,0
23,-,-,NaN,Player,3806-6478,yudam9,0,0,0.00,0
24,-,-,NaN,Player,3003-0498,Israh,0,0,0.00,0
25,-,-,NaN,Player,2136-2331,xNSFWgg,2,45,16.02,0
26,8831-1398,orchidk,NaN,Player,6974-2007,Netanel111,0,0,0.00,0
27,-,-,NaN,Master,9858-9318,TheSheepMaster,5,218,26.00,0
28,4168-5945,ALF0N50,NaN,Agent,4168-5945,ALF0N50,0,0,0.00,0
29,-,-,NaN,Player,9389-1661,Kazmozaurus,7,343,107.50,0
30,-,-,NaN,Player,6467-0988,MrDadonn,3,261,35.46,0
31,4535-3656,YoY0Mama,NaN,Agent,4535-3656,YoY0Mama,0,0,0.00,0
32,-,-,NaN,Player,9295-7063,RabbyBeni,0,0,0.00,0
33,-,-,NaN,Player,8078-2258,MarikHaPogeha,3,249,50.00,0
34,-,-,NaN,Player,9519-7806,Mr Trips!,3,86,34.81,0
35,-,-,NaN,Player,3266-1721,yoniroe,0,0,0.00,0
36,4535-3656,YoY0Mama,NaN,Player,8573-8167,nomnomnomnomnom,0,0,0.00,0

In [4]:
parser._calculate_overlay(parser.data)

C:\Users\USER\PycharmProjects\GGDataParser\src\main.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1223.71' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  rakeback_df.loc[rakeback_df.AGENT_NAME == "-", "OVERLAY"] = overlay

     AGENT_ID  AGENT_NAME  COUNTRY     ROLE  MEMBER_ID         NICKNAME  GAMES  HANDS     FEE  TOTAL_BALANCE  OVERLAY
0   3314-4813    Natsich!      NaN   Player  3852-3098        Reg Eater      0      0    0.00              0     0.00
1   3314-4813    Natsich!      NaN    Agent  3314-4813         Natsich!      1    112   12.00              0     0.00
2   9817-5561  VIVIPUTZ[]      NaN   Player  4686-9121        Enigam951      7    456  129.91              0     0.00
3   9817-5561  VIVIPUTZ[]      NaN    Agent  9817-5561       VIVIPUTZ[]      4     96   43.00              0     0.00
4           -           -      NaN  Manager  4517-4290         DaniDonk     17   1369  224.39              0  1223.71
5           -           -      NaN   Player  7259-4548           Tal122      0      0    0.00              0  1223.71
6   8831-1398     orchidk      NaN   Player  6251-5310    Shohaminio888      0      0    0.00              0     0.00
7           -           -      NaN   Player  3136-8163       ItoTheBigo     12    724   86.95              0  1223.71
8           -           -      NaN   Player  7374-8621         lil nuts      3    337   76.29              0  1223.71
9   3314-4813    Natsich!      NaN   Player  1154-1115            IDvir      4    118   33.14              0     0.00
10  8831-1398     orchidk      NaN    Agent  8831-1398          orchidk      2    115   41.76              0     0.00
11  8831-1398     orchidk      NaN   Player  5282-7593         Matan118      0      0    0.00              0     0.00
12          -           -      NaN   Player  3779-1229         Itay8764      0      0    0.00              0  1223.71
13  6353-9124  AceHighBye      NaN    Agent  6353-9124       AceHighBye      0      0    0.00              0     0.00
14          -           -      NaN  Manager  3034-8358        Sheepment     12    614  214.64              0  1223.71
15  4535-3656    YoY0Mama      NaN   Player  5218-9187         Rotem119      0      0    0.00              0     0.00
16          -           -      NaN   Player  3752-4991         HaMacabi      0      0    0.00              0  1223.71
17          -           -      NaN   Player  9194-1695       NuMaaa2000      2    195   26.84              0  1223.71
18  8831-1398     orchidk      NaN   Player  5687-1807      Kingkong325      0      0    0.00              0     0.00
19  4535-3656    YoY0Mama      NaN   Player  2922-3380     All_In_Dolev      0      0    0.00              0     0.00
20  9817-5561  VIVIPUTZ[]      NaN   Player  9442-2093      VIVIPUTZ-JR      4    228   39.00              0     0.00
21          -           -      NaN   Player  6873-6696          Krane84      1      8   16.00              0  1223.71
22          -           -      NaN   Player  2902-9205           nitayk      1    109   10.00              0  1223.71
23          -           -      NaN   Player  3806-6478           yudam9      0      0    0.00              0  1223.71
24          -           -      NaN   Player  3003-0498            Israh      0      0    0.00              0  1223.71
25          -           -      NaN   Player  2136-2331          xNSFWgg      2     45   16.02              0  1223.71
26  8831-1398     orchidk      NaN   Player  6974-2007       Netanel111      0      0    0.00              0     0.00
27          -           -      NaN   Master  9858-9318   TheSheepMaster      5    218   26.00              0  1223.71
28  4168-5945     ALF0N50      NaN    Agent  4168-5945          ALF0N50      0      0    0.00              0     0.00
29          -           -      NaN   Player  9389-1661      Kazmozaurus      7    343  107.50              0  1223.71
30          -           -      NaN   Player  6467-0988         MrDadonn      3    261   35.46              0  1223.71
31  4535-3656    YoY0Mama      NaN    Agent  4535-3656         YoY0Mama      0      0    0.00              0     0.00
32          -           -      NaN   Player  9295-7063        RabbyBeni      0      0    0.00              0  1223.71
33          -           -      NaN   Player  8078-2258    MarikHaPogeha      3    249   50.00              0  1223.71
34          -           -      NaN   Player  9519-7806        Mr Trips!      3     86   34.81              0  1223.71
35          -           -      NaN   Player  3266-1721          yoniroe      0      0    0.00              0  1223.71
36  4535-3656    YoY0Mama      NaN   Player  8573-8167  nomnomnomnomnom      0      0    0.00              0     0.00

In [30]:
import pandas as pd

def parse_excel_to_tables(file_path):
    # Load raw Excel data (no headers)
    df = pd.read_excel(file_path, header=None, sheet_name='Ring Game Detail')

    # Define a set of required table header keywords
    required_keywords = {'Player', 'Buy-in', 'Cashout', 'Hands'}

    # Create a mask of rows that contain all required header keywords
    mask = df.apply(lambda row: required_keywords.issubset(set(row.dropna().astype(str).str.strip())), axis=1)
    header_indices = df.index[mask].tolist()

    # Add the end of DataFrame as the final boundary
    header_indices.append(len(df))

    # Extract tables based on header locations
    tables = []
    for i in range(len(header_indices) - 1):
        start = header_indices[i]
        end = header_indices[i + 1]

        table = df.iloc[start:end].reset_index(drop=True)
        table.columns = table.iloc[0]  # First row is header
        table = table[1:].reset_index(drop=True)  # Drop header row

        tables.append(table)

    return tables

In [31]:
dfs = parse_excel_to_tables(parser.get_latest_file())

In [32]:
dfs[0]

0                                             Player         NaN Buy-in  Cashout Hands Insurance EV Cashout Squid Game  Bad Beat Jackpot      NaN   Rake     P&L
0                                                 ID    Nickname    NaN      NaN   NaN       NaN        NaN        NaN  Contribution Fee  Payouts    NaN     NaN
1                                          3034-8358   Sheepment    800        0    47         0          0          0                 0        0  32.64    -800
2                                          4517-4290    DaniDonk    600  1334.72    47         0          0          0                 0        0  32.64  734.72
3                                          9817-5561  VIVIPUTZ[]    200      200     0         0          0          0                 0        0      0       0
4                                              Total         NaN   1600  1534.72    94         0          0          0                 0        0  65.28  -65.28
5  Start/End Time : 2025-05-04 17:46:11 ~ 2025-05...         NaN    NaN      NaN   NaN       NaN        NaN        NaN               NaN      NaN    NaN     NaN
6  Table Name : 1/2 NLH , Creator : TheSheepMaste...         NaN    NaN      NaN   NaN       NaN        NaN        NaN               NaN      NaN    NaN     NaN
7  Table Information : Game : NLH , Blinds : 1/2 ...         NaN    NaN      NaN   NaN       NaN        NaN        NaN               NaN      NaN    NaN     NaN